namespace E33Randomizer;

/// <summary>
/// Every text of the interface in English and Russian, side by side so a change to one is easy to carry over to
/// the other. Keys are used from XAML ({e33Randomizer:Tr Key}) and from code (Loc.Get, Loc.Format).
/// </summary>
public static class UiStrings
{
    public static readonly Dictionary<string, (string En, string Ru)> All = Build(
    [
        // Main window
        ("Main_TabEnemies", "Enemy Randomizer", "Враги"),
        ("Main_TabItems", "Item Randomizer", "Предметы"),
        ("Main_TabSkills", "Skill Randomizer", "Навыки"),
        ("Main_TabMisc", "Misc", "Разное"),
        ("Main_Seed", "Seed:", "Сид:"),
        ("Main_SeedTip",
            "The seed decides every random choice. The same seed with the same settings gives the same mod. -1 picks a new seed each time; the seed used is shown after generating and written to the spoiler log.",
            "Сид определяет все случайные решения. Один и тот же сид с теми же настройками даёт один и тот же мод. -1 — каждый раз новый сид; использованный сид показывается после генерации и записывается в спойлер-лог."),
        ("Main_SaveSettings", "Save settings JSON", "Сохранить настройки"),
        ("Main_SaveSettingsTip",
            "Saves the settings of all tabs to a JSON file, to share them or come back to them later.",
            "Сохраняет настройки всех вкладок в JSON-файл, чтобы поделиться ими или вернуться к ним позже."),
        ("Main_LoadSettings", "Load settings JSON", "Загрузить настройки"),
        ("Main_LoadSettingsTip", "Loads settings saved with \"Save settings JSON\".", "Загружает настройки, сохранённые кнопкой «Сохранить настройки»."),
        ("Main_Generate", "Generate and pack mod", "Создать мод"),
        ("Main_GenerateTip",
            "Randomizes everything with the current settings and packs the mod. The mod, spoiler_log.txt and generation_log.txt go to a new folder next to the randomizer.",
            "Рандомизирует всё с текущими настройками и собирает мод. Мод, spoiler_log.txt и generation_log.txt кладутся в новую папку рядом с рандомайзером."),
        ("Main_CopyMod", "Copy the mod into the game folder:", "Копировать мод в папку игры:"),
        ("Main_CopyModTip",
            "After generating, the mod is copied into the game's Sandfall\\Content\\Paks\\~mods folder, replacing the previous randomizer mod. Just start the game.",
            "После генерации мод копируется в папку игры Sandfall\\Content\\Paks\\~mods вместо предыдущего мода рандомайзера. Остаётся только запустить игру."),
        ("Main_GameFolderTip", "The mod is copied into Sandfall\\Content\\Paks\\~mods inside this folder", "Мод копируется в Sandfall\\Content\\Paks\\~mods внутри этой папки"),
        ("Main_Browse", "Browse...", "Обзор..."),
        ("Main_BrowseTip", "Choose the game folder yourself.", "Выбрать папку игры вручную."),
        ("Main_FindSteam", "Find Steam install", "Найти в Steam"),
        ("Main_FindSteamTip", "Finds the game in your Steam libraries.", "Ищет игру в библиотеках Steam."),
        ("Main_RemoveMod", "Remove mod from game", "Удалить мод из игры"),
        ("Main_RemoveModTip",
            "Deletes the randomizer mod from the game's ~mods folder, so the game starts unmodified. Other mods and your saves aren't touched.",
            "Удаляет мод рандомайзера из папки ~mods, и игра запускается без изменений. Другие моды и сохранения не затрагиваются."),
        ("Main_CheckUpdatesOnStartup", "Check for updates on startup", "Проверять обновления при запуске"),
        ("Main_CheckUpdates", "Check for updates", "Проверить обновления"),
        ("Main_CheckUpdatesTip", "Looks for a newer release on GitHub and offers to install it.", "Ищет новую версию на GitHub и предлагает установить её."),
        ("Main_DarkTheme", "Dark theme", "Тёмная тема"),
        ("Main_Language", "Language:", "Язык:"),

        // Misc tab
        ("Misc_SaveGroup", "Save File Patching", "Исправление сохранений"),
        ("Misc_CountersText",
            "It is recommended that you patch your save file to gain access to Jump and Gradient Counters if you don't have those already.\n\nThey are located in %USERPROFILE%/AppData/Local/Sandfall/Saved/SaveGames/[numbers]/ and are named \"EXPEDITION_[save slot id]\".\nThere's also a Backup folder that contains all of your \"Load Previous Saves\" saves. Simply press the button and choose the save file that you want to patch.",
            "Рекомендуется пропатчить сохранение, чтобы получить контратаки после прыжка и градиентные контратаки, если их у вас ещё нет.\n\nСохранения лежат в %USERPROFILE%/AppData/Local/Sandfall/Saved/SaveGames/[цифры]/ и называются \"EXPEDITION_[номер слота]\".\nТам же есть папка Backup со всеми сохранениями из «Загрузить предыдущие сохранения». Нажмите кнопку и выберите сохранение, которое нужно пропатчить."),
        ("Misc_AddCounters", "Add counters to save file", "Добавить контратаки"),
        ("Misc_CurtainText",
            "If you have triggered the second phase of Act III Renoir, then the curtain in Lumière's Opera House will be closed, preventing you from finishing the game.\nUse this button to fix that.",
            "Если вы запустили вторую фазу боя с Ренуаром в третьем акте, занавес в опере Люмьера закроется, и пройти игру будет нельзя.\nЭта кнопка это исправляет."),
        ("Misc_FixCurtain", "Fix curtains in save file", "Открыть занавес"),

        // Enemies tab
        ("En_Randomize", "Randomize enemies", "Рандомизировать врагов"),
        ("En_RandomizeTip",
            "Replaces the enemies of fights following the placement rules (\"Customize Enemy Placements\" below).",
            "Заменяет врагов в боях по правилам расстановки (кнопка «Настроить расстановку врагов» внизу)."),
        ("En_Sizes", "Randomize encounter sizes", "Случайное число врагов в бою"),
        ("En_SizesTip",
            "Each fight gets a random number of enemies, chosen from the sizes ticked on the right.",
            "Каждый бой получает случайное число врагов из отмеченных справа вариантов."),
        ("En_SizeOptionTip", "Fights may have this many enemies", "Бои могут быть с таким числом врагов"),
        ("En_SizesNonRandom", "Randomize size of encounters that don't contain randomized enemies", "Менять размер боёв, в которых нет рандомизируемых врагов"),
        ("En_SizesNonRandomTip",
            "Also changes the number of enemies in fights where every enemy is set to \"Not Randomized\" in the placement rules.",
            "Менять число врагов и в боях, где все враги отмечены в правилах расстановки как «Не рандомизировать»."),
        ("En_KeepBossSizes", "Only change the size of enemy packs, keep boss and miniboss fights as they are", "Менять размер только обычных групп, бои с боссами и мини-боссами не трогать"),
        ("En_KeepBossSizesTip",
            "Fights with a boss or a chromatic boss, and fights with only minibosses, keep their original number of enemies.",
            "Бои с боссом или хроматическим боссом, а также бои только с мини-боссами сохраняют исходное число врагов."),
        ("En_Merchants", "Randomize merchant fights", "Рандомизировать бои с торговцами"),
        ("En_MerchantsTip",
            "The duels with merchants (which unlock their special wares) get random enemies too.",
            "Дуэли с торговцами (открывающие их особые товары) тоже получают случайных врагов."),
        ("En_LootWarning",
            "Merchants' special wares unlocks and Maelle's paintress skills are considered loot drops. It is recommended that you only disable this if you are also running an item randomizer.",
            "Открытие особых товаров торговцев и навыки Маэль считаются добычей с врагов. Отключать это рекомендуется, только если вы также рандомизируете предметы."),
        ("En_CutContent", "Include cut content (gets overriden by custom placement)", "Включить вырезанный контент (правила расстановки важнее)"),
        ("En_CutContentTip",
            "Enemies that were cut from the game can appear as replacements, unless the placement rules say otherwise.",
            "Враги, вырезанные из игры, тоже могут попасться на замену, если правила расстановки не говорят иначе."),
        ("En_CutContentWarning",
            "Be careful when parrying cut content enemies, as it can break their AI. You can replace broken enemies in Edit Encounters window.",
            "Осторожно с парированием вырезанных врагов: это может сломать их ИИ. Сломанных врагов можно заменить в окне редактирования боёв."),
        ("En_Onslaught", "Enable enemy onslaught", "Натиск врагов"),
        ("En_OnslaughtTip", "Adds extra enemies to every fight.", "Добавляет в каждый бой дополнительных врагов."),
        ("En_OnslaughtWarning",
            "The game has full support for 4 enemies, but the 5th and beyond gets lumped into a single spot outside the fighting arena. They will still function properly except that you won't be able to see their attacks or shoot them.",
            "Игра полностью поддерживает до 4 врагов. Пятый и следующие стоят в одной точке за пределами арены: они работают, но их атак не видно и по ним нельзя стрелять."),
        ("En_RandomizeAdded", "Randomize added enemies", "Рандомизировать добавленных врагов"),
        ("En_RandomizeAddedTip",
            "Off: the added enemies are copies of the fight's enemies. On: each added enemy is picked separately.",
            "Выключено: добавленные враги — копии врагов этого боя. Включено: каждый добавленный враг выбирается отдельно."),
        ("En_AdditionalCount", "Number of additional enemies:", "Сколько врагов добавить:"),
        ("En_Cap", "Cap encounter size at:", "Максимум врагов в бою:"),
        ("En_CapTip", "No fight gets more enemies than this.", "Ни в одном бою не будет больше врагов, чем здесь указано."),
        ("En_EnsureBosses", "Ensure that boss encounters have at least one boss", "В боях с боссом всегда есть хотя бы один босс"),
        ("En_EnsureBossesTip",
            "If the replacements leave a boss fight without a boss, its first enemy becomes a random boss. This ignores the placement rules, but never uses excluded enemies.",
            "Если после замены в бою с боссом не осталось босса, первый враг становится случайным боссом. Правила расстановки при этом не учитываются, но исключённые враги не используются."),
        ("En_ReduceBossRepetition", "Reduce boss repetition (ignores frequency adjustments)", "Меньше повторов боссов (игнорирует настройки частоты)"),
        ("En_ReduceBossRepetitionTip",
            "Bosses are drawn from a pool without repeats: a boss appears again only after every boss was used.",
            "Боссы берутся из пула без повторов: босс встретится снова, только когда будут использованы все."),
        ("En_KeepStory", "Keep scripted story battles (Gustave vs Renoir, the final duel)", "Не трогать сюжетные бои (Густав против Ренуара, финальная дуэль)"),
        ("En_KeepStoryTip",
            "Randomizing them can break the scripted outcome. Tutorial fights are randomized.",
            "Их рандомизация может сломать сценарий боя. Обучающие бои рандомизируются."),
        ("En_MatchArchetype",
            "Replacements take the strength of the enemy they replace (a chromatic in place of a chromatic, an elite in place of an elite)",
            "Замена получает силу заменённого врага (хроматик на месте хроматика, элита на месте элиты)"),
        ("En_MatchArchetypeTip",
            "A replacement gets the archetype of the enemy it replaces, so its stats match: enemy stats come from the archetype and the fight's level.",
            "Замена получает архетип заменённого врага, поэтому характеристики совпадают: статы врага зависят от архетипа и уровня боя."),
        ("En_Giants", "Only put giant enemies into fights that had a giant (Gargant, Glissando, the Paintress...)", "Гигантов ставить только туда, где был гигант (Гаргант, Глиссандо, Художница...)"),
        ("En_GiantsTip",
            "Giants (the Giant Enemies/Bosses category) don't fit small arenas. They only appear in fights whose arena held a giant in the original game, one per fight.",
            "Гиганты (категория Giant Enemies/Bosses) не помещаются на маленьких аренах. Они появляются только в боях, где на арене был гигант в оригинальной игре, по одному на бой."),
        ("En_KeepDrops", "Keep fights whose enemies drop progression items (merchant unlocks, Maelle's painter skills)", "Не трогать бои, где враги дают важные предметы (товары торговцев, навыки Маэль)"),
        ("En_KeepDropsTip",
            "Drops belong to the enemy, so randomizing these fights would make the drops impossible to get.",
            "Добыча привязана к врагу, поэтому после рандомизации таких боёв её было бы не получить."),
        ("En_SimonP2", "Replace Phase 2 Simon with Phase 1 in mandatory fights until after the Lune tutorial fight", "До обучающего боя с Люне заменять Симона второй фазы на первую в обязательных боях"),
        ("En_SimonP2Tip",
            "Phase 2 Simon is far too strong for the first mandatory fights of the game.",
            "Симон второй фазы слишком силён для первых обязательных боёв."),
        ("En_CustomizePlacement", "Customize Enemy Placements", "Настроить расстановку врагов"),
        ("En_CustomizePlacementTip",
            "Rules for which enemies replace which, how often each appears, and which are never randomized or never used.",
            "Правила: какие враги кого заменяют, как часто встречаются, кого не рандомизировать и кого не использовать."),
        ("En_EditEncounters", "Edit Individual Encounters", "Редактировать бои"),
        ("En_EditEncountersTip",
            "Shows the enemies of every fight after randomizing, and lets you change them by hand before packing the mod.",
            "Показывает врагов каждого боя после рандомизации и позволяет поменять их вручную перед сборкой мода."),

        // Items tab
        ("It_Randomize", "Randomize items", "Рандомизировать предметы"),
        ("It_RandomizeTip",
            "Shuffles the items of chests, dialogues, merchants, enemy drops and other rewards following the placement rules.",
            "Перемешивает предметы в сундуках, диалогах, у торговцев, в добыче врагов и других наградах по правилам расстановки."),
        ("It_Visible", "Make every item show a pick up notification", "Показывать уведомление о каждом полученном предмете"),
        ("It_VisibleTip",
            "The game hides the notification for some items; with this on you always see what you got.",
            "Игра не показывает уведомление для некоторых предметов; с этой настройкой вы всегда видите, что получили."),
        ("It_CutContent", "Include cut content items", "Включить вырезанные предметы"),
        ("It_CutContentTip", "Items that were cut from the game can be placed too.", "Предметы, вырезанные из игры, тоже могут попасться."),
        ("It_PaintedPower", "Receive Painted Power at the start of Act III", "Получить Painted Power в начале третьего акта"),
        ("It_PaintedPowerTip",
            "Painted Power lets damage go past 9999. In the original game you get it at the start of Act III; this keeps it there in addition to the randomized items.",
            "Painted Power позволяет наносить больше 9999 урона. В оригинале её дают в начале третьего акта; настройка оставляет её там вдобавок к случайным предметам."),
        ("It_StartWeapons", "Randomize starting weapons", "Случайное стартовое оружие"),
        ("It_StartWeaponsTip", "The characters start with random weapons of their own.", "Персонажи начинают со случайным собственным оружием."),
        ("It_StartWeaponsWarning", "Gustave's weapon will be behind him when he wakes up at the start of Act I", "Оружие Густава будет лежать позади него, когда он очнётся в начале первого акта"),
        ("It_StartCosmetics", "Randomize starting cosmetics", "Случайный стартовый внешний вид"),
        ("It_StartCosmeticsTip", "The characters start with random outfits and haircuts.", "Персонажи начинают со случайными костюмами и причёсками."),
        ("It_PrologueGear", "Enable gear rolls in prologue (they will be level 16 and can drastically alter the difficulty)", "Разрешить снаряжение в прологе (оно будет 16 уровня и может сильно изменить сложность)"),
        ("It_PrologueGearTip",
            "Off: weapons and pictos that would land in the prologue (Lumière chests and dialogues, the Gommage) are replaced with a basic upgrade material.",
            "Выключено: оружие и пикто, попавшие в пролог (сундуки и диалоги Люмьера, Гоммаж), заменяются простым материалом улучшения."),
        ("It_GestralBeach", "Randomize gestral beach rewards", "Рандомизировать награды пляжей гестралов"),
        ("It_GestralBeachTip", "Rewards of the Gestral beach minigames (races, volleyball and the others).", "Награды мини-игр на пляжах гестралов (гонки, волейбол и другие)."),
        ("It_ChecksSizeNonRandom", "Change number of items in non-randomized checks", "Менять число предметов в нерандомизируемых точках"),
        ("It_ChecksSizeNonRandomTip",
            "The \"Randomize number of...\" options below also apply to checks that only hold items set to \"Not Randomized\".",
            "Настройки «Случайное число...» ниже применяются и к точкам, где лежат только предметы, отмеченные как «Не рандомизировать»."),
        ("It_KeyLogic", "Guarantee that all key items can be obtained (key item logic)", "Гарантировать получение всех ключевых предметов (логика)"),
        ("It_KeyLogicTip",
            "Each key item is placed once, never in places that can't be revisited, and never behind a check that needs it. Overrides key item repetition.",
            "Каждый ключевой предмет кладётся один раз, никогда — туда, куда нельзя вернуться, и никогда — за точку, которой он сам нужен. Перекрывает настройку повторов ключевых предметов."),
        ("It_KeyRepetition", "Reduce key item repetition", "Меньше повторов ключевых предметов"),
        ("It_KeyRepetitionTip",
            "Key items are drawn from a pool without repeats. Not used when the key item logic is on.",
            "Ключевые предметы берутся из пула без повторов. Не действует, когда включена логика ключевых предметов."),
        ("It_MerchantLocked", "Make any of the merchant wares locked", "Делать товары торговцев закрытыми"),
        ("It_MerchantLockedTip",
            "Each merchant ware has this chance to need the merchant beaten in a duel before it can be bought.",
            "Каждый товар с такой вероятностью становится доступен только после победы над торговцем в дуэли."),
        ("It_WithProbability", "with probability", "с вероятностью"),
        ("It_MerchantSize", "Randomize merchant inventory sizes", "Случайный размер ассортимента торговцев"),
        ("It_LootDrops", "Randomize number of loot drops", "Случайное число предметов в добыче врагов"),
        ("It_Tower", "Randomize number of the Endless Tower rewards", "Случайное число наград Бесконечной башни"),
        ("It_Chests", "Randomize number of items per map pickup", "Случайное число предметов в находках на карте"),
        ("It_Actions", "Randomize number of cutscene rewards", "Случайное число наград за сценки"),
        ("It_Quantity", "Randomize quantities of upgrade materials", "Случайное количество материалов улучшения"),
        ("It_Between", "between", "от"),
        ("It_And", "and", "до"),
        ("It_CustomizePlacement", "Customize Item Placements", "Настроить расстановку предметов"),
        ("It_CustomizePlacementTip",
            "Rules for which items replace which, how often each appears, and which are never randomized or never used.",
            "Правила: какие предметы что заменяют, как часто встречаются, что не рандомизировать и что не использовать."),
        ("It_EditChecks", "Edit Individual Checks", "Редактировать точки"),
        ("It_EditChecksTip",
            "Shows the items of every check after randomizing, and lets you change them by hand before packing the mod.",
            "Показывает предметы каждой точки после рандомизации и позволяет поменять их вручную перед сборкой мода."),

        // Skills tab
        ("Sk_Randomize", "Randomize skills", "Рандомизировать навыки"),
        ("Sk_RandomizeTip",
            "Shuffles the skills of the characters' skill trees following the placement rules. Julie's tree isn't changed.",
            "Перемешивает навыки в деревьях персонажей по правилам расстановки. Дерево Жюли не меняется."),
        ("Sk_ReduceRepetition", "Reduce skill duplication", "Меньше повторов навыков"),
        ("Sk_ReduceRepetitionTip",
            "A skill appears at most once in each character's tree, when there are enough skills to choose from.",
            "Навык встречается в дереве персонажа не больше одного раза, если есть из чего выбирать."),
        ("Sk_Overcharge", "Keep Gustave's Overcharge", "Оставить Густаву Overcharge"),
        ("Sk_OverchargeTip", "Gustave's Overcharge stays on its starting node.", "Overcharge Густава остаётся на своём начальном месте."),
        ("Sk_CutContent", "Include cut content skills", "Включить вырезанные навыки"),
        ("Sk_CutContentTip", "Skills that were cut from the game can appear in the trees. They may not work properly.", "Вырезанные из игры навыки тоже могут попасть в деревья. Они могут работать неправильно."),
        ("Sk_CustomizePlacement", "Customize Skill Placements", "Настроить расстановку навыков"),
        ("Sk_CustomizePlacementTip",
            "Rules for which skills replace which, how often each appears, and which are never randomized or never used.",
            "Правила: какие навыки что заменяют, как часто встречаются, что не рандомизировать и что не использовать."),
        ("Sk_EditTrees", "Edit Individual Skill Trees", "Редактировать деревья навыков"),
        ("Sk_EditTreesTip",
            "Shows every skill tree after randomizing, and lets you change it by hand before packing the mod.",
            "Показывает каждое дерево навыков после рандомизации и позволяет поменять его вручную перед сборкой мода."),

        // Custom placement window
        ("Cp_Title", "Custom Placement", "Правила расстановки"),
        ("Cp_SpecialRules", "Special Rules", "Особые правила"),
        ("Cp_NotRandomized", "Not Randomized:", "Не рандомизировать:"),
        ("Cp_NotRandomizedTip", "These stay where they are in the original game.", "Эти остаются на своих местах, как в оригинальной игре."),
        ("Cp_Excluded", "Excluded:", "Не использовать:"),
        ("Cp_ExcludedTip", "These are never picked as replacements.", "Эти никогда не выбираются на замену."),
        ("Cp_Remove", "Remove", "Убрать"),
        ("Cp_QuickPresets", "Quick Presets", "Готовые пресеты"),
        ("Cp_OopsAll", "Oops All", "Все — это"),
        ("Cp_OopsAllTip", "Replaces the rules: everything becomes the object chosen on the right.", "Заменяет правила: всё превращается в выбранный справа объект."),
        ("Cp_CustomPlacement", "Custom Placement", "Свои правила"),
        ("Cp_Selected", "Selected", "Что заменяется"),
        ("Cp_ReplacedBy", "Is Replaced By", "На что заменяется"),
        ("Cp_ReplacedByTip",
            "The chances of what the selected object or category becomes, in percent.",
            "Вероятности, во что превращается выбранный объект или категория, в процентах."),
        ("Cp_NothingSelected", "Nothing selected", "Ничего не выбрано"),
        ("Cp_SelectedObject", "Selected: {0}", "Выбрано: {0}"),
        ("Cp_AddPlacementRow", "+ Add Placement Row", "+ Добавить замену"),
        ("Cp_Frequency", "Frequency Adjustment", "Частота"),
        ("Cp_FrequencyTip",
            "Makes objects appear more or less often as replacements: the percentage multiplies their normal chance.",
            "Объекты будут попадаться на замену чаще или реже: процент умножает их обычный шанс."),
        ("Cp_AddFrequencyRow", "+ Add Frequency Row", "+ Добавить частоту"),
        ("Cp_PresetJson", "Preset JSON", "JSON пресета"),
        ("Cp_LoadPreset", "Load Preset JSON", "Загрузить пресет"),
        ("Cp_SavePreset", "Save Preset JSON", "Сохранить пресет"),
        ("Cp_Close", "Close", "Закрыть"),
        ("Cp_AlreadyInList", "{0} is already in the list.", "{0} уже есть в списке."),
        ("Cp_AlreadyInListTitle", "Already added", "Уже добавлено"),
        ("Cp_SelectObjectFirst", "Please select an object from the dropdown first.", "Сначала выберите объект в списке."),
        ("Cp_PresetErrorRevert", "Error loading preset: {0}; Reverting to Default.", "Ошибка загрузки пресета: {0}. Возвращены правила по умолчанию."),
        ("Cp_LoadDialogTitle", "Load Custom Preset", "Загрузить пресет"),
        ("Cp_SaveDialogTitle", "Save Custom Preset", "Сохранить пресет"),
        ("Preset_Splitcategoriesdefault", "Split categories (default)", "По умолчанию"),
        ("Preset_Totalrandomness", "Total randomness", "Полный хаос"),
        ("Preset_10ofregularenemiesarebosses", "10% of regular enemies are bosses", "10% обычных врагов — боссы"),
        ("Preset_Makeeveryenemyaboss", "Make every enemy a boss", "Каждый враг — босс"),
        ("Preset_Onlychangepictosandweapons", "Only change pictos and weapons", "Менять только пикто и оружие"),
        ("Preset_Addmorepictos", "Add more pictos", "Больше пикто"),
        ("Preset_Dontchangegradients", "Don't change gradients", "Не менять градиентные атаки"),
        ("Preset_Feetforeveryone", "Feet for everyone", "Всем по ногам"),
        ("Preset_Custompreset1", "Custom preset 1", "Свой пресет 1"),
        ("Preset_Custompreset2", "Custom preset 2", "Свой пресет 2"),

        // Edit individual encounters, checks and skill trees
        ("Ed_Encounter_Title", "Edit individual encounters", "Редактирование боёв"),
        ("Ed_Encounter_Search", "Search by encounter or enemy names:", "Поиск по бою или врагу:"),
        ("Ed_Encounter_Containers", "Encounters", "Бои"),
        ("Ed_Encounter_Objects", "Enemies in the encounter", "Враги в бою"),
        ("Ed_Encounter_Add", "Add enemy:", "Добавить врага:"),
        ("Ed_Encounter_Load", "Load encounters from .txt file", "Загрузить бои из .txt"),
        ("Ed_Encounter_Save", "Save encounters to .txt file", "Сохранить бои в .txt"),
        ("Ed_Check_Title", "Edit individual checks", "Редактирование точек"),
        ("Ed_Check_Search", "Search by check or item names:", "Поиск по точке или предмету:"),
        ("Ed_Check_Containers", "Checks", "Точки"),
        ("Ed_Check_Objects", "Items in the check", "Предметы в точке"),
        ("Ed_Check_Add", "Add item:", "Добавить предмет:"),
        ("Ed_Check_Load", "Load checks from .txt file", "Загрузить точки из .txt"),
        ("Ed_Check_Save", "Save checks to .txt file", "Сохранить точки в .txt"),
        ("Ed_SkillTree_Title", "Edit individual skill trees", "Редактирование деревьев навыков"),
        ("Ed_SkillTree_Search", "Search by skill tree or skill names:", "Поиск по дереву или навыку:"),
        ("Ed_SkillTree_Containers", "Skill Trees", "Деревья навыков"),
        ("Ed_SkillTree_Objects", "Skills in the skill tree", "Навыки в дереве"),
        ("Ed_SkillTree_Add", "Add skill:", "Добавить навык:"),
        ("Ed_SkillTree_Load", "Load skill trees from .txt file", "Загрузить деревья из .txt"),
        ("Ed_SkillTree_Save", "Save skill trees to .txt file", "Сохранить деревья в .txt"),
        ("Ed_TxtTip", "The text file lists every one of them with its contents, so it can be edited and loaded back.", "В текстовом файле перечислены все они с содержимым: его можно отредактировать и загрузить обратно."),
        ("Ed_Reroll", "Reroll with current settings", "Перебросить заново"),
        ("Ed_RerollTip", "Randomizes this part again with the current settings, discarding the changes made here.", "Заново рандомизирует эту часть с текущими настройками; правки, сделанные здесь, теряются."),
        ("Ed_Pack", "Generate mod files from current", "Создать мод из текущего"),
        ("Ed_PackTip", "Packs the mod exactly as shown here, without randomizing again.", "Собирает мод ровно в том виде, как показано здесь, без новой рандомизации."),
        ("Ed_RemoveTip", "Remove", "Убрать"),
        ("Ed_LoadTxtTitle", "Load TXT", "Загрузить TXT"),
        ("Ed_SaveTxtTitle", "Save TXT", "Сохранить TXT"),
        ("Ed_TxtSaved", "TXT saved successfully!", "Файл TXT сохранён."),
        ("Ed_TxtLoadError", "Error loading TXT: {0}", "Ошибка загрузки TXT: {0}"),
        ("Ed_TxtSaveError", "Error saving TXT: {0}", "Ошибка сохранения TXT: {0}"),
        ("Ed_RerollError", "Error generating: {0}", "Ошибка генерации: {0}"),
        ("Ed_RerollErrorTitle", "Reroll Error", "Ошибка перебрасывания"),
        ("Ed_PackError", "Error packing: {0}", "Ошибка сборки: {0}"),
        ("Ed_PackErrorTitle", "Packing Error", "Ошибка сборки"),

        // Messages
        ("Msg_StartError", "Error starting: {0}", "Ошибка запуска: {0}"),
        ("Msg_LoadingErrorTitle", "Loading Error", "Ошибка загрузки"),
        ("Msg_LoadError", "Error loading: {0}", "Ошибка загрузки: {0}"),
        ("Msg_SaveError", "Error saving: {0}", "Ошибка сохранения: {0}"),
        ("Msg_SavingErrorTitle", "Saving Error", "Ошибка сохранения"),
        ("Msg_LoadErrorTitle", "Load Error", "Ошибка загрузки"),
        ("Msg_SaveErrorTitle", "Save Error", "Ошибка сохранения"),
        ("Msg_SaveCompleteTitle", "Save Complete", "Сохранено"),
        ("Msg_NothingSelectedTitle", "Nothing selected", "Ничего не выбрано"),
        ("Msg_JsonFilter", "JSON files (*.json)|*.json|All files (*.*)|*.*", "Файлы JSON (*.json)|*.json|Все файлы (*.*)|*.*"),
        ("Msg_TxtFilter", "Text files (*.txt)|*.txt|All files (*.*)|*.*", "Текстовые файлы (*.txt)|*.txt|Все файлы (*.*)|*.*"),
        ("Msg_LoadPresetTitle", "Load Preset", "Загрузить настройки"),
        ("Msg_SavePresetTitle", "Save Preset", "Сохранить настройки"),
        ("Msg_PresetSaved", "Preset saved successfully!", "Сохранено."),
        ("Msg_PresetLoadError", "Error loading preset: {0}", "Ошибка загрузки: {0}"),
        ("Msg_PresetSaveError", "Error saving preset: {0}", "Ошибка сохранения: {0}"),
        ("Msg_GenerationDone",
            "Generation done! You can find the mod, spoiler_log.txt and generation_log.txt in the {0} folder.\n\n{1}Used Seed: {2}\n",
            "Готово! Мод, spoiler_log.txt и generation_log.txt лежат в папке {0}.\n\n{1}Сид: {2}\n"),
        ("Msg_GenerationDoneTitle", "Generation Summary", "Генерация завершена"),
        ("Msg_GenerationError", "Error generating: {0}\n\nDetails are in {1}", "Ошибка генерации: {0}\n\nПодробности в {1}"),
        ("Msg_GenerationErrorTitle", "Generating Error", "Ошибка генерации"),
        ("Msg_ModCopied", "The mod was copied into {0}, just start the game.\n\n", "Мод скопирован в {0}, можно запускать игру.\n\n"),
        ("Msg_NoGameFolder",
            "The game folder isn't set, so the mod wasn't copied into the game. Set it at the bottom of the main window.\n\n",
            "Папка игры не указана, поэтому мод не скопирован в игру. Укажите её внизу главного окна.\n\n"),
        ("Msg_OutdatedGameFiles",
            "WARNING: your game has newer versions of {0} files this mod replaces (the game was probably updated after this version of the randomizer). The mod may crash the game or remove new content; check for a randomizer update. The files are listed in generation_log.txt.\n\n",
            "ВНИМАНИЕ: в вашей игре более новые версии {0} файлов, которые заменяет мод (видимо, игра обновилась после выхода этой версии рандомайзера). Мод может ронять игру или убирать новый контент; проверьте обновление рандомайзера. Список файлов — в generation_log.txt.\n\n"),
        ("Msg_SelectGameFolder", "Select the Expedition 33 game folder", "Выберите папку игры Expedition 33"),
        ("Msg_WrongFolder", "This isn't the Expedition 33 game folder: it has no Sandfall\\Content\\Paks inside.", "Это не папка игры Expedition 33: внутри нет Sandfall\\Content\\Paks."),
        ("Msg_WrongFolderTitle", "Wrong folder", "Не та папка"),
        ("Msg_GameNotFound", "Couldn't find a Steam installation of Expedition 33. Use Browse to select the game folder.", "Не удалось найти Expedition 33 в Steam. Выберите папку игры кнопкой «Обзор...»."),
        ("Msg_GameNotFoundTitle", "Game not found", "Игра не найдена"),
        ("Msg_CopyFailed", "Couldn't copy the mod into {0}. Close the game and try again. ({1})", "Не удалось скопировать мод в {0}. Закройте игру и попробуйте ещё раз. ({1})"),
        ("Msg_RemoveModTitle", "Remove mod", "Удаление мода"),
        ("Msg_RemoveNoFolder", "The game folder isn't set. Choose it with Browse or Find Steam install.", "Папка игры не указана. Выберите её кнопкой «Обзор...» или «Найти в Steam»."),
        ("Msg_RemoveNothing", "There is no randomizer mod in {0}.", "В {0} нет мода рандомайзера."),
        ("Msg_RemoveConfirm",
            "Remove the randomizer mod from {0}?\n\nThe game will start unmodified. Other mods and your saves aren't touched.",
            "Удалить мод рандомайзера из {0}?\n\nИгра будет запускаться без изменений. Другие моды и сохранения не затрагиваются."),
        ("Msg_RemoveDone", "The randomizer mod was removed from the game.", "Мод рандомайзера удалён из игры."),
        ("Msg_RemoveFailed", "Couldn't remove the mod: {0}\n\nClose the game and try again.", "Не удалось удалить мод: {0}\n\nЗакройте игру и попробуйте ещё раз."),
        ("Msg_SelectSaveFile", "Select save file", "Выберите сохранение"),
        ("Msg_SaveFilter", "SAV files (*.sav)|*.sav|All files (*.*)|*.*", "Сохранения (*.sav)|*.sav|Все файлы (*.*)|*.*"),
        ("Msg_SavePatched", "Save File Patched! The original save was kept as {0}.bak", "Сохранение исправлено! Оригинал сохранён как {0}.bak"),
        ("Msg_SavePatchedTitle", "Patched", "Готово"),
        ("Msg_SavePatchError", "Error patching: {0}", "Ошибка исправления: {0}"),
        ("Msg_SavePatchErrorTitle", "Patching Error", "Ошибка исправления"),

        // Tracker
        ("Misc_TrackerGroup", "Tracker", "Трекер"),
        ("Misc_TrackerText",
            "The tracker follows your run of the seed generated last: key items, every place with items by region, and hints where the key items are. It can read your game saves to mark found key items and visited areas by itself.",
            "Трекер следит за прохождением последнего сгенерированного сида: ключевые предметы, все места с предметами по регионам и подсказки, где лежат ключевые предметы. Он может читать сохранения игры и сам отмечать найденные ключевые предметы и посещённые места."),
        ("Misc_EnableTracker", "Enable the tracker", "Включить трекер"),
        ("Misc_OpenTracker", "Open tracker", "Открыть трекер"),
        ("Msg_NoTrackerSeed",
            "There is no generated seed to track yet. Generate the mod first: the tracker follows the seed generated last.",
            "Пока нет сгенерированного сида для трекера. Сначала создайте мод: трекер следит за последним сгенерированным сидом."),
        ("Tr_WindowTitle", "E33 Randomizer — Tracker", "E33 Randomizer — Трекер"),
        ("Tr_Title", "Tracker", "Трекер"),
        ("Tr_Minimize", "Minimize", "Свернуть"),
        ("Tr_Maximize", "Maximize", "Развернуть"),
        ("Tr_Close", "Close", "Закрыть"),
        ("Tr_Seed", "Seed {0}", "Сид {0}"),
        ("Tr_Total", "Marked {0} / {1}", "Отмечено {0} / {1}"),
        ("Tr_KeyItems", "Key items", "Ключевые предметы"),
        ("Tr_KeyItemTip", "Click to mark as found. With tracking from saves on, items in the inventory are marked by themselves.", "Нажмите, чтобы отметить найденным. При отслеживании по сохранениям предметы из инвентаря отмечаются сами."),
        ("Tr_HintTip", "Hint: show where this item is in this seed (a spoiler)", "Подсказка: показать, где лежит этот предмет в этом сиде (спойлер)"),
        ("Tr_HintOriginalPlace", "In its original place", "На своём обычном месте"),
        ("Tr_HintPickup", "{0}, where the original game had {1}", "{0}, там, где в оригинале было: {1}"),
        ("Tr_HintOther", "{0}: {1}", "{0}: {1}"),
        ("Tr_NamesNote", "Pickups are named after what the original game had there.", "Находки подписаны тем, что лежало там в оригинальной игре."),
        ("Tr_Regions", "Regions", "Регионы"),
        ("Tr_Act0", "Prologue", "Пролог"),
        ("Tr_Act1", "Act I", "Акт I"),
        ("Tr_Act2", "Act II", "Акт II"),
        ("Tr_Act3", "Act III", "Акт III"),
        ("Tr_Act4", "Finale", "Финал"),
        ("Tr_PickRegion", "Choose a region", "Выберите регион"),
        ("Tr_HideDone", "Hide marked", "Скрыть отмеченное"),
        ("Tr_RegionSubtitle", "{0} · {1} · {2} of {3} marked", "{0} · {1} · отмечено {2} из {3}"),
        ("Tr_Visited", "visited", "посещено"),
        ("Tr_NotVisited", "not visited yet", "ещё не посещено"),
        ("Tr_Requires", "Needs: {0}", "Нужно: {0}"),
        ("Tr_Type_Mappickups", "Pickup", "Находка"),
        ("Tr_Type_Merchantinventories", "Merchant", "Торговец"),
        ("Tr_Type_Dialoguerewards", "Dialogue", "Диалог"),
        ("Tr_Type_Cutscenerewards", "Cutscene", "Сценка"),
        ("Tr_Type_Endlesstowerrewards", "Tower", "Башня"),
        ("Tr_Type_Enemydrops", "Enemy", "Враг"),
        ("Tr_AutoTrack", "Track from game saves", "Отслеживать по сохранениям"),
        ("Tr_AutoTrackTip",
            "Each time the game saves, the tracker reads the newest save: key items in the inventory are marked as found and the areas you've been to as visited. Chests and other places are marked by hand, since the save doesn't tell which of them were taken.",
            "Каждый раз, когда игра сохраняется, трекер читает новое сохранение: ключевые предметы из инвентаря отмечаются найденными, а места, где вы были, — посещёнными. Сундуки и остальные места отмечаются вручную: по сохранению нельзя понять, какие из них уже взяты."),
        ("Tr_Watching", "Waiting for the game to save…", "Ждём сохранения игры…"),
        ("Tr_NoSaves", @"No game saves found (the Steam version keeps them in AppData\Local\Sandfall)", @"Сохранения игры не найдены (версия Steam хранит их в AppData\Local\Sandfall)"),
        ("Tr_SaveRead", "{0}, saved at {1} · key items in the inventory: {2}", "{0}, сохранено в {1} · ключевых предметов в инвентаре: {2}"),
        ("Tr_SaveError", "Couldn't read the save: {0}", "Не удалось прочитать сохранение: {0}"),
        ("Tr_OpenSeed", "Another seed…", "Другой сид…"),
        ("Tr_OpenSeedTip", "Open the tracker of another generated seed (a rand_ folder next to the randomizer).", "Открыть трекер другого сгенерированного сида (папка rand_ рядом с рандомайзером)."),
        ("Tr_OpenSeedDialog", "Choose a generated seed folder (rand_...)", "Выберите папку сгенерированного сида (rand_...)"),
        ("Tr_NoTrackerData", "This folder has no tracker data. Choose a rand_ folder generated by v1.3.7 or newer.", "В этой папке нет данных трекера. Выберите папку rand_, созданную версией 1.3.7 или новее."),
        ("Tr_Reset", "Reset progress", "Сбросить прогресс"),
        ("Tr_ResetConfirm", "Click again to reset", "Нажмите ещё раз для сброса"),

        // Updates
        ("Upd_Title", "Updates", "Обновления"),
        ("Upd_Done", "The randomizer was updated to v{0}.", "Рандомайзер обновлён до v{0}."),
        ("Upd_DoneTitle", "Update complete", "Обновление завершено"),
        ("Upd_InstallFailed", "The update couldn't be installed: {0}\n\nYou can download it from {1}", "Не удалось установить обновление: {0}\n\nЕго можно скачать отсюда: {1}"),
        ("Upd_InstallFailedTitle", "Update failed", "Ошибка обновления"),
        ("Upd_DevBuild", "This is a development build, it isn't updated automatically. Update it with git pull.", "Это сборка для разработки, она не обновляется автоматически. Обновите её через git pull."),
        ("Upd_CheckFailed", "Couldn't check for updates: {0}", "Не удалось проверить обновления: {0}"),
        ("Upd_Latest", "You have the latest version (v{0}).", "У вас последняя версия (v{0})."),
        ("Upd_Available", "Version {0} is available (you have v{1}).\n\n{2}\n\nDownload and install it now? The randomizer will restart.", "Доступна версия {0} (у вас v{1}).\n\n{2}\n\nСкачать и установить сейчас? Рандомайзер перезапустится."),
        ("Upd_AvailableTitle", "Update available", "Доступно обновление"),
        ("Upd_CantWrite", "The randomizer can't replace its files in {0}. Move it to a folder you can write to, or download the update from {1}", "Рандомайзер не может заменить свои файлы в {0}. Перенесите его в папку с правом записи или скачайте обновление отсюда: {1}"),
        ("Upd_Downloading", "Downloading {0}...", "Загрузка {0}..."),
        ("Upd_DownloadingProgress", "Downloading {0}... {1:P0}", "Загрузка {0}... {1:P0}"),
        ("Upd_Installing", "Installing, the randomizer will restart...", "Установка, рандомайзер перезапустится..."),
        ("Upd_Failed", "Update failed: {0}", "Ошибка обновления: {0}"),
        ("Upd_WindowTitle", "Updating E33 Randomizer", "Обновление E33 Randomizer"),
    ]);

    private static Dictionary<string, (string En, string Ru)> Build((string Key, string En, string Ru)[] entries)
    {
        return entries.ToDictionary(e => e.Key, e => (e.En, e.Ru));
    }
}
